name: Security scan

on: [push]

permissions:
  contents: read          # To checkout and code read
  actions: read           # To read execution Github Actions context
  security-events: write  # To upload SARIF files into GHAS 

jobs:
  reusable_semgrep_workflow:
    name: SAST scan in pre-prod
    uses: ./.github/workflows/semgrep.yml
    with:
      working-directory: '.'
      env: pre-prod
      severity-threshold-config: 'all'
      severity-threshold-blocking: 'high'
  reusable_security_workflow:
    name: Several security checks
    uses: ./.github/workflows/security_scan.yml
    with:
      working-directory: '.'
      
